---
title: "interaction_type between males and females"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r load packages}
library(hyenaR)
library(tidyverse)
library(lubridate)
```

```{r load database}
# load database from master thesis
load_package_database.full(db.path = "/data/Fisidata26082022.sqlite")
# sexual_interactions <- extract_database_table("interactions")%>% filter(!is.na(sexual))
sexual_interactions <- read_csv(file = "/Users/lizimai/Google Drive/My Drive/MEME/Work/Projects/Berlin Hyena/Database/rawData26082022/interactions.csv") %>% filter(!is.na(sexual))
```

```{r check interaction_type between females and males}
sexual_interactions %>% 
  group_by(sexual) %>% 
  count() %>% 
  arrange(-n)
# define ids
# identify party 1 is not in ids
# identify party 2 is not in ids
# categories of non-id patterns
# define multiple ids
```

```{r}
sexual_interactions %>% 
  filter(!sexual %in% c("ambiguous","at the kill", "bait very soft", "bait?", "def?","shad?","T-212","soft shadowing","mating?","foll?","bait soft")) %>% 
  mutate(sexual = case_when(
    sexual == "foll (+mating?)" ~ "foll",
    sexual == "foll+mating?" ~ "foll",
    sexual == "shadowing/mating?" ~ "shadowing",
    TRUE ~ sexual
  )) %>% 
 mutate(interactionID = paste0("int_",1:n()),
        interaction_type = str_extract_all(sexual, pattern = "[A-Za-z]+"),
        list_ID1 = str_extract_all(party1, pattern = "[:alpha:]\\-[:digit:]{3}",),
        list_ID2 = str_extract_all(party2, pattern = "[:alpha:]\\-[:digit:]{3}",),
        num_int = lengths(interaction_type),
        num_ID1 = lengths(list_ID1),
        num_ID2 = lengths(list_ID2)) %>% 
  filter(num_int != 0 & num_ID1 !=0 & num_ID2 !=0) %>% 
  unnest_longer(interaction_type) %>% 
  unnest_longer(list_ID1) %>% 
  unnest_longer(list_ID2) -> sexualInteractionsClean_temp


sexualInteractionsClean_temp %>%   
  drop_na(list_ID1, list_ID2) %>% 
  mutate(
    interaction_type = case_when(
      interaction_type == "foll" ~ "following",
      interaction_type == "bait" ~ "baiting",
      interaction_type == "shad" ~ "shadowing",
      interaction_type == "def" ~ "defending",
      interaction_type == "mount" ~ "mounting",
      interaction_type == "follow" ~ "following",
      interaction_type == "maiting" ~ "mating",
      interaction_type == "defend" ~ "defending",
      interaction_type == "shadow" ~ "shadowing",
      interaction_type == "harass" ~ "harassment",
      TRUE ~ interaction_type),
    sex_ID1 = fetch_id_sex(list_ID1),
    sex_ID2 = fetch_id_sex(list_ID2),
      ) %>%
  filter(sex_ID1 != sex_ID2) %>% 
  mutate(female = if_else(sex_ID1 == "female", list_ID1, list_ID2),
         male = if_else(sex_ID1 == "male", list_ID1, list_ID2),
         date = as_date(date, format = "%d.%m.%y"),
         date_time = as_datetime(paste(date, time)),
         num_ind = num_ID1 + num_ID2) %>% 
  select(interactionID, female, male, interaction_type, date, date_time, num_int, num_ind, interaction) -> sexualInteractionsClean
  
save(sexualInteractionsClean, file = "data/sexualInteractionsClean.RData")

#-> sexual_interaction_type_clean
  # group_by(interaction_type) %>%
  # count() %>%
  # arrange(-n)
# following, baiting, shadowing, defending, mating, mounting
```


```{r}
load("data/sexualInteractionsClean.RData")
sexualInteractionsClean %>% 
  mutate(
    clan = hyenaR::fetch_id_clan.current(female, at = date, censored.to.last.clan = TRUE),
    with_suitable_male = hyenaMC::fetch_dyad_is.rule.fitting.mate(female, male)) -> sexualInteractionsClean_temp
  
candidatesOnInteraction <- hyenaMC::create_id_mate.candidate(sexualInteractionsClean_temp$female, date = sexualInteractionsClean_temp$date,  sexualInteractionsClean_temp$clan)

save(candidatesOnInteraction, file = "data/candidatesOnInteraction.RData")

```

```{r}
load(file = "data/candidatesOnInteraction.RData")
candidatesOnInteraction %>% 
  mutate(male_is_suitable =  fetch_dyad_is.rule.fitting.mate(femaleID, candidateID)) -> candidatesOnInteraction_temp

candidatesOnInteraction_temp %>% 
  group_by(femaleID, date) %>% 
  summarise(num_candidate = n(),
            num_suit_candidate = sum(male_is_suitable),
            num_na_candidate = sum(is.na(male_is_suitable))) -> candidatesOnInteraction_summary

thresholdrank <- c(1/3, 2/3)

left_join(sexualInteractionsClean_temp, candidatesOnInteraction_summary, by = c("female" = "femaleID", "date" = "date")) %>% 
  mutate(ratio_suit_cand = num_suit_candidate/num_candidate,
         male_rank_std = hyenaR::fetch_id_rank.std(ID = male, at = date),
        male_rank_cat = hyenaR::recode_rank.std_rank.cat(male_rank_std, thresholdrank),
        female_rank_std = hyenaR::fetch_id_rank.std(ID = female, at = date),
        female_rank_cat = hyenaR::recode_rank.std_rank.cat(female_rank_std, thresholdrank),
        female_is_right_censored = hyenaR::fetch_id_is.censored.right(female),
        female_parity = fetch_id_parity(femaleID = female, date = date),
        female_parity_cat = case_when(
          female_parity == 1 ~ "Primiparious",
          female_parity > 1 ~ "Pluriparious",
          TRUE ~ NA_character_)
        )-> sexualInteractionsFull

save(sexualInteractionsFull, file = "data/sexualInteractionsFull.RData")
```

```{r}
ggplot(sexualInteractionsFull, aes(x = date, fill = interaction_type)) +
  geom_histogram(bins = 70)
 
ggplot(sexualInteractionsFull, aes(x = date, fill = clan)) +
  geom_histogram()
```


